### ISSUE TITLE
[SUPPORT] Add own mime.types file

### ISSUE THREAD

**Issue by DavidSporer** [million12/docker-nginx#4]
Hi,

how can I add my own mime.types file.
I want to add application/vnd.apple.pkpass    pkpass; to the mime.types file of nginx.
One idea was to add it to the 10-mime.conf file in my build.sh script that is executed after the container is started but I'm sure there's a better way.

Thanks,
David

**Comment by ryzy** [comment]
Hi David,

Are you building your own image based on this one (`FROM million12/nginx`)?

Mime types are loaded from `container-files/etc/nginx/nginx.d/10-mime.conf`.
Override it in your sub-image and add lines with your mimes, e.g.:

```
include /etc/nginx/mime.types;
default_type application/octet-stream;
types {
    application/vnd.apple.pkpass pkpass;
}
```

You'll get a merge of whatever is in `/etc/nginx/mime.types` + your types.

Hope it helps.

**Comment by DavidSporer** [comment]
Thanks Marcin!
I'm building my image from million12/typo3-flow-neos-abstract:php70.
I ended up adding one config file with a volume and copying the configuration file to the correct folder on startup because it's easier to change that during development.

**Comment by pozgo** [comment]
closing as no longer an issue since custom config is available.
