### ISSUE TITLE
Nginx status calls every second

### ISSUE THREAD

**Issue by cqcwillard** [million12/docker-nginx#5]
I'm having a hard time finding a way to turn off a curl request that is going to "nginx_status" every second.  It seems to be tied to supervisor's call "nginx -t && nginx -s reload"; is this normal behavior?

**Comment by ryzy** [comment]
Hi!

Sorry, but I don't understand what exactly do you mean. What's that curl request?

Indeed, there's an `inotify` process watching for changes in both /etc/nginx/ and /data/conf/nginx/ locations and then does `nginx -t && nginx -s reload`.

If you get it constantly executed.. that means you have changes in these locations all the time?

**Comment by cqcwillard** [comment]
Hey,

Thank you for your prompt response!  So, the odd thing is we don't have changes that occur in those folder paths that you mentioned, except the first time the containers fire up.   When I look at the docker logs, I can see that curl request is happening every second to the "/nginx_status" endpoint, and it appears to be related to the supervisor configuration.  

Please see the attached screenshot; the cors error is not the problem, however it does show that a request is happening at a regular interval.

![screen shot 2016-08-04 at 9 29 53 am](https://cloud.githubusercontent.com/assets/11064196/17403808/49f39ce4-5a27-11e6-8cca-8a86620795d6.png)

**Comment by ryzy** [comment]
I see.

I'd say the request to /nginx_status has nothing to do with supervisor etc ;)

It's simply request which is done by someone from somewhere. You probably have set up some monitoring which does that :) That image itself doesn't do anything like that.

**Comment by ryzy** [comment]
That supervisor command to reload Nginx does something else (completely reloads Nginx configuration) and you'd see it clearly in your log messages, with appropriate info: this and that file changed, full Nginx processes status after reload (very similar from those during Nginx start up).

**Comment by cqcwillard** [comment]
So it seems it has something to do with Nginx restarting.  I have no monitoring enabled, in fact I'm just running the image by itself.  If I remove the line that causes the reload in supervisor then I don't see the requests any longer.

**Comment by ryzy** [comment]
That's weird indeed.

Can you provide command you launch the image so I can observe that issue? I can't replicate it, when I launch the image, after Nginx startup messages the log console stays quiet.

**Comment by cqcwillard** [comment]
Actually I think you may have hit the nail on the head earlier.  I checked the access logs and found this gem: 

`127.0.0.1 - - [04/Aug/2016:14:22:22 +0000] "GET /nginx_status/ HTTP/1.1" 404 31
"-" "Sysdig Agent/1.0"`

It appears that there is an agent hitting that endpoint after all.

Thank you for your help!

**Comment by adminjena** [comment]
@million12   How to fix this issue ? Even I have found same error in my environment. So searching details and found that you solved it. could you please guide me on the same error : 

2021/01/19 02:30:33 [error] 14#14: *1432481 "/usr/share/nginx/html/nginx_status/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /nginx_status/ HTTP/1.1", host: "localhost"

**Comment by pozgo** [comment]
I don't think there is `index.html` on that path. 

Try without
